### PR TITLE
Fix segfault when minidump fails to process

### LINKED ISSUE #37: minidump-stackwalk segfaults when minidump is 0 bytes
The leftpad changes for #30 cause minidump-stackwalk to segfault when the minidump is 0-bytes.

https://bugzilla.mozilla.org/show_bug.cgi?id=1713104

Example crash reports:

* fef248b7-cd01-498a-bc77-353b80210527
* 6caa9e0b-c983-4225-9e2d-0c5c00210526

### PR DESCRIPTION
**Pull request by willkg**
When the minidump fails to process, then querying `system_info()` segfaults. Best to check the processing result first.

Before this change, stackwalk segfaults on 0-byte minidumps like what we have with fef248b7-cd01-498a-bc77-353b80210527 and 6caa9e0b-c983-4225-9e2d-0c5c00210526.

After this change, stackwalk spits out:

```
{"sensitive":{},"status":"ERROR_NO_MINIDUMP_HEADER"}
```

Fixes #37.

### CODE REVIEW

File: minidump-stackwalk/stackwalker.cc [hunk 1]
```diff
@@ -1452,6 +1450,11 @@ int main(int argc, char** argv)
   ProcessResult result =
     minidump_processor.Process(&minidump, &process_state);
 
+  int minidump_width = 64;
```
Comment (willkg) [inline minidump-stackwalk/stackwalker.cc:1453]: This defaults `minidump_width` to 64. In the case of a processing error, I'm pretty sure stackwalk doesn't spit out any addresses, so it's kind of moot.

**Review by Gankra — APPROVED** [review]

**Comment by willkg** [comment]
Thank you!
